sudo: required
language: ruby
rvm: 2.2.3

services:
  - docker

before_install:
  - docker --version
  - docker build -t kylemanna/openvpn .
  - docker inspect kylemanna/openvpn
  - docker run kylemanna/openvpn openvpn --version || true # why does it returns 1?
  - docker run kylemanna/openvpn openssl version

script: bundle exec cucumber
